name: Ci

on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --prod --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test:cov
      - name: Upload articat
        uses: actions/upload-artifact@v2
        with:
          path: .jest-coverage
          name: report-coverage
